python-stat_tool should runtime depend on libboost_python-dev
Otherwise the build fails on Mac with

ImportError: dlopen(/Users/aaronmeurer/anaconda3/conda-bld/python-stat_tool_1519597713025/_t_env/lib/python2.7/site-packages/stat_tool/__stat_tool.so, 2): Library not loaded: @rpath/libboost_python.dylib
  Referenced from: /Users/aaronmeurer/anaconda3/conda-bld/python-stat_tool_1519597713025/_t_env/lib/python2.7/site-packages/stat_tool/__stat_tool.so
  Reason: image not found